//
// Created by kmakara on 01/06/24.
//

#ifndef COMPILATIONSERVER_CONSTANTS_H
#define COMPILATIONSERVER_CONSTANTS_H

#define INITIAL_BUFFER_SIZE 2048
#define MAX_COMMAND_LENGTH 1024
#define MAX_BINARY_NAME_LENGTH 128
#define MAX_RETRIES 5
#define RETRY_DELAY 1
#define MAX_SERVERS 100

#define PORT 8080
#define SERVER_DIRECTORY "/tmp/compilation_server"
#define MAX_CLIENTS 1

#endif //COMPILATIONSERVER_CONSTANTS_H
